services:

  nextjs:
    build: ./next-js
    ports:
      - 3001:3000

  django:
    build: ./django
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8000:8000

  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379

  postgres:
    build: ./postgres
    # restart: on-failure
    # container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata: